config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :edit, :update, :show] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end

  
  get 'search' => 'search#search'
  get 'home/about' => 'homes#about'

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  geocoded_by :address
  after_validation :geocode

  attachment :profile_image
  validates :name, presence: true, length: {in: 2..20}
  validates :introduction, length:{maximum: 50}
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  	@book = Book.new
    @user= current_user
  end

  def show
  	@book = Book.new
  	@user = User.find(params[:id])
  end

  def edit
  	@user = User.find(params[:id])
    if @user.id != current_user.id
    redirect_to user_path(current_user.id)
  end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
  	redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def following
    @user = User.find(params[:id])
    @users = @user.followings
    @book = Book.new
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    @book = Book.new
  end

	private
	def user_params
		params.require(:user).permit(:name, :profile_image, :introduction)
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<table class="table">
  <tr>
    <th>image</th>
    <th>name</th>
    <th></th>
  </tr>
  <% users.each do |user| %>
  <tr>
    <td width="250"><%= attachment_image_tag user, :profile_image, :fill, 40, 40, format: 'jpeg',fallback: "no_image_copy.jpg" %></td>
    <td width="200"><%= user.name %></td>
    <td>フォロー数：<%= user.follower.count %></td>
    <td>フォロワー数：<%= user.followed.count %></td>
    <td>
      <% if current_user != user %>
        <% if current_user.following?(user) %>
          <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete %>
        <% else %>
          <%= link_to 'フォローする', user_relationships_path(user.id), method: :POST %>
        <% end %>
      <% end %>
    </td>
    <td>
      <%= link_to "Show", user_path(user) %>
    </td>
  </tr>
  <% end %>
</table>

app/views/users/edit.html.erb
<div class="container">
  <% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
	<div class="row">
		<h1>User info</h1>
		<div class="row">
    <% if @user.errors.any? %>
      <div class="error_explanation">
        <h2><%= @user.errors.count %>errors prohibited this obj from being saved:</h2>
        <ul>
          <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>
			<%=form_for(@user) do |f|%>
			<div class="field">
			<%= f.label :name %>
			<%=f.text_field :name, class:"form-control" %>
			</div>
			<div class="field">
			<%= f.label :Image %>
			<%= f.attachment_field :profile_image %>
			</div>
			<div class="field">
			<%= f.label :introduction %>
			<%= f.text_area :introduction, class:"form-control" %>
			</div>
			<%= f.submit "Update User",class:"btn btn-update-user  btn-base-1 mt-20" %>
			<% end %>
		</div>
	</div>

app/views/users/index.html.erb
<div class="container">
	<div class="row">
			<%= render 'books/sidebar', book: @book , user: @user%>
		<div class="col-xs-9">
			<h1>Users</h1>
				<%= render 'index',users: @users %>
		</div>
	</div>
</div>

app/views/users/show.html.erb
<div class="container">
<% if flash[:notice] %>
      <div class="flash" >
        <%= flash[:notice] %>
      </div>
    <% end %>
		<div class="row">
			<%= render 'books/sidebar', book: @book, user: @user %>
		<div class="col-xs-9">
			<h1>Books</h1>
				<table class="table" width="750">
					<tr border-bottom="1">
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th></th>
					</tr>
					<tr>
					<% @user.books.each do |book| %>
					<td><%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg',fallback: "no_image_copy.jpg" %></td>
					<td>
						<%= link_to book_path(book) do %>
						<%= book.title %></td>
						<% end %>
					<td><%= book.body %></td>
					<td></td>
					<td>コメント数：<%=book.book_comments.count%></td>
					</tr>
					<% end %>
				</table>
		</div>
	  </div>
	  <% if @user == current_user %>
  <div class="row">
  	<h1>Your Map</h1>
  	<div id='map'></div>
  	<style>
#map {
  height: 600px;
  width: 600px;
}
</style>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCPFFOwtkmL_EWmYi9pTQJw35PPlqfXa8o&callback=initMap" async defer></script>
  	<script>
  		function initMap(){
  let map = new google.maps.Map(document.getElementById('map'),{
    center: {lat: -34.397, lng: 150.644},
    zoom: 8,
  });
}
  	</script>
  </div>
  <% end %>
  </div>
</div>