config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :edit, :update, :show] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end

  
  get 'search' => 'search#search'
  get 'home/about' => 'homes#about'

end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search)
    if search
      where(['title LIKE?', "%#{search}%"])
    else
      all
    end
  end
  validates :title, presence: true
  validates :body, presence: true, length:{maximum: 199}
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
def create
	@book = Book.new(book_params)
	@book.user_id = current_user.id
  if @book.save
  	flash[:notice] = "You have creatad book successfully."
	redirect_to book_path(@book)
	else
		@books = Book.all
		@user = current_user
		render :index
	end
end

def index
	@books = Book.all
	@book = Book.new
end

def show
	@find = Book.find(params[:id])
	@book = Book.new
	@book_comment = BookComment.new
end

def edit
	@book = Book.find(params[:id])
	if @book.user_id != current_user.id
		redirect_to books_path
	end
end

def update
	@book = Book.find(params[:id])
	if @book.update(book_params)
		flash[:notice] = "You have updated book successfully."
	redirect_to book_path(@book)
	else
		render :edit
	end
end

def destroy
	@book = Book.find(params[:id])
	@book.destroy
	redirect_to books_path
end

private
def book_params
	params.require(:book).permit(:title, :body)
end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comments.html.erb
<% find.book_comments.each do |comment| %>
<tr id="comment-<%= comment.id %>">
  <td><%= attachment_image_tag comment.user, :profile_image, :fill, 40, 40, format: 'jpeg',fallback: "no_image_copy.jpg" %><br><%= comment.user.name %></td>
  <td width="400"><%= comment.comment %></td>
  <% if comment.user == current_user %>
  <td><%= link_to book_book_comment_path(@find, comment), method: :delete, remote: true do %>
    <button type="button" class="btn btn-destroy active">Destroy</button>
   <% end %>
  </td>
  <% end %>
<% end %>
</tr>

app/views/books/_error_message.html.erb
<div class="row">
    <% if book.errors.any? %>
      <div class="error_explanation">
        <h2><%= book.errors.count %>errors prohibited this obj from being saved:</h2>
        <ul>
          <% book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  </div>

app/views/books/_favorite.html.erb
<%if book.favorited_by?(current_user)%>
      <%= link_to book_favorites_path(book), method: :delete, remote: true do %>
        <i class="fas fa-heart" aria-hidden="true" style="color: red;"></i>
        <%= book.favorites.count %>
      <% end %>
    <% else %>
      <%= link_to book_favorites_path(book), method: :post, remote: true do %>
        <i class="far fa-heart" aria-hidden="true"></i>
        <%= book.favorites.count %>
      <% end %>
    <% end %>

app/views/books/_index.html.erb
<table class="table" width="400">
  <tr>
  <th></th>
  <th>Title</th>
  <th>Opinion</th>
  <th></th>
  <th></th>
  </tr>
  <% books.each do |book| %>
  <tr>
   <td width="70">
    <%= link_to user_path(book.user_id) do %>
    <%= attachment_image_tag book.user, :profile_image, :fill, 40, 40, format: 'jpeg',fallback: "no_image_copy.jpg" %>
    <% end %>
   </td>
   <td width="70">
      <%= link_to book_path(book) do %>
       <%= book.title %>
      <% end %>
   </td>
   <td width="70">
     <%= book.body %>
   </td>
   <td id="favorite-<%= book.id %>">
    <%= render 'books/favorite', book: book %>
   </td>
   <td>コメント数：<%=book.book_comments.count%></td>
  </tr>
  <% end %>
</table>

app/views/books/_sidebar.html.erb
		<div class="col-xs-3">
			<div class="userinfo">
				<h2>User info</h2>
				<div>
					<%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg',fallback: "no_image_copy.jpg" %>
				</div>
				<table width="250">
					<tr>
						<td><strong>name</strong></td>
						<td><strong><%= user.name %></strong></td>
					</tr>
					<tr>
						<td><strong>introduction</strong></td>
						<td><strong><%= user.introduction %></strong></td>
					</tr>
					<tr>
						<td>following</td>
						<td>
							<%= link_to user_follows_path(user) do %>
								<%= user.follower.count %>
							<% end %>
						</td>
					</tr>
					<tr>
						<td>followers</td>
						<td>
							<%= link_to user_followers_path(user) do %>
								<%= user.followed.count %>
							<% end %>
						</td>
					</tr>
				</table>
				<% if user.id == current_user.id %>
				<div>
					<%= link_to(edit_user_path(user)) do %><button type="button" class="btn btn-edit btn-block active"><span class="glyphicon glyphicon-wrench" aria-hidden="true"></span></button>
					<% end %>
				</div>
				<% else %>
					<% unless current_user == user %>
             <% if current_user.following?(user) %>
             	<%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete, class:"btn btn-block" %>
             <% else %>
             	<%= link_to 'フォローする',user_relationships_path(user.id), method: :POST, class:"btn btn-block" %>
             <% end %>
          <% end %>
				<% end %>
			</div>
			<div class="newbook">
				<h2>New book</h2>
				<%= form_for(book) do |f| %>
					<div>
						<h5>Title</h5>
						<%= f.text_field :title, class:"form-control" %>
					</div>
					<div>
						<h5>Opinion</h5>
						<%= f.text_area :body,class:"form-control" %>
					</div>
					<div>
						<%= f.submit "Create Book", class:"form-control btn btn-create btn-base-1 mt-20",rows:"3" %>
					</div>
					<% end %>
			</div>
		</div>

app/views/books/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
		<h1>Editing Book</h1>
		<div>
		<%= render 'books/error_message', book: @book %>
		</div>
		<div>
		<%= form_for(@book) do |f| %>
		<h4>Title</h4>
		<%= f.text_field :title, autofocus: true, class:"form-control"%>
		<h4>Opinion</h4>
		<%= f.text_area :body ,autofocus: true, class:"form-control" %>
		<%= f.submit "Update Book", class:"btn btn-update-book btn-block btn-base-1 mt-20" %>
		<% end %>
		</div>
		<div class="showback">
		<%= link_to "Show", book_path(@book) %>
		<span>|</span>
		<%= link_to"Back", books_path %>
		</div>
	</div>
	</div>
</div>

app/views/books/index.html.erb
<div class="container">
	<% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>

	<%= render 'books/error_message', book: @book %>
	<div class="row">
			<%= render 'books/sidebar', book: @book, user: current_user %>
		<div class="col-xs-9">
			<h1>Books</h1>
				<%= render 'index', books: @books %>
		</div>
	</div>
</div>

app/views/books/show.html.erb
<div class="container">
	<% if flash[:notice] %>
      <div class="flash">
        <%= flash[:notice] %>
      </div>
    <% end %>
	<div class="row">
			<%= render 'books/sidebar', book: @book, user: @find.user %>
		<div class="col-xs-9">
			<h1>Book detail</h1>
				<table class="table" width="600">
					<tr>
						<td width="200"><%= link_to(user_path(@find.user_id))do %>
							<%= attachment_image_tag @find.user, :profile_image, :fill, 40, 40, format: 'jpeg',fallback: "no_image_copy.jpg" %><br><%= @find.user.name %>
							<% end %>
						</td>
						<td width="70">
							<%= link_to(book_path(@find))  do%>
							<%= @find.title %>
							<% end %>
						</td>
						<td width="70"><%= @find.body %></td>
						<td><%= render 'books/favorite', book: @find %></td>
						<td>コメント数：<%= @find.book_comments.count %></td>
						<% if @find.user == current_user %>
						<td>
							<%= link_to(edit_book_path(@find)) do %><button type="button" class="btn btn-edit2 active">Edit</button>
							<% end %>
						</td>
						<td><%= link_to book_path(@find), method: :delete, "data-confirm" => "本当に消しますか？" do %>
							<button type="button" class="btn btn-destroy active">Destroy</button>
							<% end %>
						</td>
						<% end %>
					</tr>
				</table>
				<h1>コメント</h1>
				<table id="js-table-comment" class="table">
				<%= render 'books/comments', find: @find, book_comment: @book_comment %>
				</table>
				<%= form_with(model:[@find, @book_comment], remote: true) do |c| %>
  				<div class="row">
    				<%= c.text_area :comment, rows:'5', class:"form-control" %>
  				</div>
    			<%= c.submit "送信する",class: "btn btn-comment-destroy active " %>
				<%end%>
		</div>
	</div>
</div>