config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'homes#top'
  resources :books, only: [:create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
  resources :users, only: [:index, :edit, :update, :show] do
    resource :relationships, only: [:create, :destroy]
    get 'follows' => 'relationships#follower', as: 'follows'
    get 'followers' => 'relationships#followed', as: 'followers'
  end

  
  get 'search' => 'search#search'
  get 'home/about' => 'homes#about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  def self.search(search)
    if search
      where(['title LIKE?', "%#{search}%"])
    else
      all
    end
  end
  validates :title, presence: true
  validates :body, presence: true, length:{maximum: 199}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: 'User'


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :follower, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followed, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :following_user, through: :follower, source: :followed
  has_many :follower_user, through: :followed, source: :follower

  def follow(user_id)
    follower.create(followed_id: user_id)
  end

  def unfollow(user_id)
    follower.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    following_user.include?(user)
  end

  include JpPrefecture
  jp_prefecture :prefecture_code

  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  geocoded_by :address
  after_validation :geocode

  attachment :profile_image
  validates :name, presence: true, length: {in: 2..20}
  validates :introduction, length:{maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	def after_sign_in_path_for(resource)
		flash[:notice] = "Signed In successfully"
		user_path(@user)
	end

	def after_sign_out_path_for(resource)
		root_path
	end
	protected
	def configure_permitted_parameters
		devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :postcode, :prefecture_name, :address_city, :address_street, :address_building, :latitude, :longitude])
	end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
def create
	@book = Book.new(book_params)
	@book.user_id = current_user.id
  if @book.save
  	flash[:notice] = "You have creatad book successfully."
	redirect_to book_path(@book)
	else
		@books = Book.all
		@user = current_user
		render :index
	end
end

def index
	@books = Book.all
	@book = Book.new
end

def show
	@find = Book.find(params[:id])
	@book = Book.new
	@book_comment = BookComment.new
end

def edit
	@book = Book.find(params[:id])
	if @book.user_id != current_user.id
		redirect_to books_path
	end
end

def update
	@book = Book.find(params[:id])
	if @book.update(book_params)
		flash[:notice] = "You have updated book successfully."
	redirect_to book_path(@book)
	else
		render :edit
	end
end

def destroy
	@book = Book.find(params[:id])
	@book.destroy
	redirect_to books_path
end

private
def book_params
	params.require(:book).permit(:title, :body)
end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  	

  end

  def about
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!

  def search
    @model = params["search"]["model"]
    @content = params["search"]["content"]
    @method = params["search"]["method"]
    @records = search_for(@model, @content, @method)
  end

  private
  def search_for(model, content, method)
    if model == 'user'
      if method == 'perfect'
        User.where(name: content)
      elsif method == 'forward'
        User.where('name LIKE ?', content+'%')
      elsif method == 'backward'
        User.where('name LIKE ?', '%'+content)
      else
        User.where('name LIKE ?', '%'+content+'%')
      end
    elsif model == 'book'
      if method == 'perfect'
        Book.where(title: content)
      elsif method == 'forward'
        Book.where('title LIKE ?', content+'%')
      elsif method == 'backward'
        Book.where('title LIKE ?', '%'+content)
      else
        Book.where('title LIKE ?', '%'+content+'%')
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all
  	@book = Book.new
    @user= current_user
  end

  def show
  	@book = Book.new
  	@user = User.find(params[:id])
  end

  def edit
  	@user = User.find(params[:id])
    if @user.id != current_user.id
    redirect_to user_path(current_user.id)
  end
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
  	redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def following
    @user = User.find(params[:id])
    @users = @user.followings
    @book = Book.new
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    @book = Book.new
  end

	private
	def user_params
		params.require(:user).permit(:name, :profile_image, :introduction)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">
      <nav class= "nav navbar-nav navbar-left" >
        <span class="bookers">Bookers</span>
      </nav>
      <nav>
      <ul class="nav navbar-nav navbar-right" data-hover="dropdown" data-animations="zoomIn fadeIn fadeInUp fadeIn">
      <% if user_signed_in? %>
      <li class="icon">
        <%= link_to(user_path(current_user))do %>
        <span class="glyphicon glyphicon-home" aria-hidden="true"><span class="icon-text">Home</span></span>
        <% end %>
      </li>
      <li class="icon">
        <%= link_to(users_path)do %>
        <span class="glyphicon glyphicon-user" aria-hidden="true"><span class="icon-text">Users</span></span>
        <% end %>
      </li>
      <li class="icon">
        <%= link_to(books_path)do %>
        <span class="glyphicon glyphicon-book" aria-hidden="true"><span class="icon-text">Books</span></span>
        <% end %>
      </li>
      <li class="icon">
        <%= link_to destroy_user_session_path, method: :delete do %>
        <span class="glyphicon glyphicon-log-out" aria-hidden="true"><span class="icon-text">logout</span></span>
      <% end %>
      </li>
      <% else %>
      <li class="icon">
        <%= link_to(root_path)do %>
        <span class="glyphicon glyphicon-home" aria-hidden="true"><span class="icon-text">Home</span></span>
        <% end %>
      </li>
      <li class="icon">
        <%= link_to(home_about_path)do %>
        <span class="glyphicon glyphicon-link" aria-hidden="true"><span class="icon-text">About</span></span>
        <% end %>
      </li>
      <li class="icon">
        <%= link_to(new_user_registration_path)do %>
        <span class="glyphicon glyphicon-edit" aria-hidden="true"><span class="icon-text">sign up</span></span>
        <% end %>
      </li>
      <li>
        <%= link_to(new_user_session_path)do %>
        <span class="glyphicon glyphicon-log-in" aria-hidden="true"><span class="icon-text">login</span></span>
        <% end %>
      </li>
      <% end %>
      </ul>
      </nav>
    </div>
  </header>
  <% if user_signed_in? %>
  <div class="search-form">
    <%= form_tag(search_path, method: :get) do %>
      <%= text_field_tag 'search[content]' %>
      <%= select_tag 'search[model]', options_for_select({ "User" => "user", "Book" => "book" }) %>
      <%= select_tag 'search[method]', options_for_select({ "完全一致" => "perfect", "前方一致" => "forward", "後方一致" => "backward", "部分一致" => "partial" }) %>
      <%= submit_tag '検索' %>
    <% end %>
  </div>
  <% end %>
  <!-- /header -->
  <body>
    <%= yield %>
  </body>
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-xs-3 col-xs-offset-9">
          <p>CopyRight Infratop.inc</p>
        </div>
      </div>
    </div>
  </footer>
</html>